all:
  configuration:
    degustation:
      always_identifiant_table: true
      conformite:
        - CONFORME
        - NONCONFORME_MINEUR
        - NONCONFORME_MAJEUR
        - NONCONFORME_GRAVE
        - NONTYPICITE_CEPAGE
        - NONCONFORME_ANALYTIQUE
      has_notification: true
