all:
  configuration:
    habilitation:
      activites:
         PRODUCTEUR: "Producteur"
         VINIFICATEUR: "Vinificateur"
         VRAC: "Vrac"
         CONDITIONNEUR: "Conditionneur"
         ELABORATEUR: "Élaborateur"
         VENTE_A_LA_TIREUSE: "Vente tireuse"
      demande:
        statuts:
          DEPOT: "Dépôt"
          RELANCE_1: "Relance n°1"
          RELANCE_2: "Relance n°2"
          RELANCE_3: "Relance n°3"
          COMPLET: "Complet"
          ENREGISTREMENT: "Enregistrement"
          TRANSMIS_CI: "Transmis au Contrôle Interne"
          TRAITE_CI: "Traité par le Contrôle Interne"
          TRANSMIS_OIVR: "Transmis à l'OIVR"
          AVIS_CONFORME_OIVR: "Avis conforme de l'OIVR"
          AVIS_NONCONFORME_OIVR: "Avis non conforme de l'OIVR"
          TRANSMIS_VINO: "Transmis à VINOMED"
          AVIS_CONFORME_VINO: "Avis conforme de VINOMED"
          AVIS_NONCONFORME_VINO: "Avis non conforme de VINOMED"
          TRANSMIS_ODG: "Transmis à une autre ODG"
          VALIDE_ODG: "Validé par une autre ODG"
          REFUSE_ODG: "Refusé par une autre ODG"
          TRANSMIS_CERTIPAQ: "Transmis à CERTIPAQ"
          VALIDE_CERTIPAQ: "Validé par CERTIPAQ"
          REFUSE_CERTIPAQ: "Refusé par CERTIPAQ"
          TRANSMIS_INAO: "Transmis à l'INAO"
          VALIDE_INAO: "Validé par l'INAO"
          REFUSE_INAO: "Refusé par l'INAO"
          SUSPENDU_INAO: "Suspendu par l'INAO"
          VALIDE: "Validé"
          REFUSE: "Refusé"
          ANNULE: "Annulé"
        automatique:
          COMPLET: ENREGISTREMENT
          AVIS_CONFORME_OIVR: TRANSMIS_INAO
          AVIS_NONCONFORME_OIVR: TRANSMIS_INAO
          AVIS_CONFORME_VINO: TRANSMIS_INAO
          AVIS_NONCONFORME_VINO: TRANSMIS_INAO
          VALIDE_ODG: VALIDE
          REFUSE_ODG: REFUSE
          VALIDE_INAO: VALIDE
          REFUSE_INAO: REFUSE
          VALIDE_CERTIPAQ: VALIDE
          REFUSE_CERTIPAQ: REFUSE
        habilitations:
          HABILITATION:
            COMPLET: DEMANDE_HABILITATION
            VALIDE: HABILITE
            REFUSE: REFUS
            ANNULE: ANNULÉ
            SUSPENDU_INAO: SUSPENDU
          RETRAIT:
            COMPLET: DEMANDE_RETRAIT
            VALIDE: RETRAIT
            REFUSE: HABILITE
            ANNULE: HABILITE
            SUSPENDU_INAO: SUSPENDU
          RESILIATION:
            COMPLET: DEMANDE_RESILIATION
            VALIDE: RESILIE
            REFUSE: HABILITE
            ANNULE: HABILITE
            SUSPENDU_INAO: SUSPENDU
