all:
  configuration:
    region:
      odg:
        COTEDURHONE:
          nom: "Syndicat des Vignerons des Côtes du Rhône"
          adresse: "6 rue des Trois Faucons - CS 60093, 84918 Avignon Cedex 9"
          telephone: "%app_drev_COTEDURHONE_telephone%"
          email: "%app_drev_COTEDURHONE_email%"
          produits:
            - "TRANQ/appellations/CDR"
            - "TRANQ/appellations/CVG"
          habilitation_produits: "/Côtes du Rhône/"
        BEAUMESVENISE:
          nom: "Conservatoire AOC Beaumes Venise"
          adresse: "Place du marché à coté de la poste, 84190 Beaumes-de-Venise"
          telephone: "%app_drev_BEAUMESVENISE_telephone%"
          email: "%app_drev_BEAUMESVENISE_email%"
          produits:
            - "TRANQ/appellations/BEA"
            - "VDN/appellations/VDB"
          habilitation_produits: "/Beaumes de Venise/"
        CAIRANNE:
          nom: "Syndicat de l’AOC Cairanne"
          adresse: "6 place des Vignerons, 84290 CAIRANNE"
          telephone: "%app_drev_CAIRANNE_telephone%"
          email: "%app_drev_CAIRANNE_email%"
          produits:
            - "TRANQ/appellations/CAR"
          habilitation_produits:  "/Cairanne/"
        VINSOBRES:
          nom: "Comité des Vignerons de Vinsobres"
          adresse: "8 rue Gironde, 26110 Vinsobres"
          telephone: "%app_drev_VINSOBRES_telephone%"
          email: "%app_drev_VINSOBRES_email%"
          produits:
            - "TRANQ/appellations/VBR"
          habilitation_produits: "/Vinsobres/"
        CHATEAUNEUF:
          nom: "Syndicat des Vignerons de Châteauneuf-du-Pape"
          adresse: "25 avenue Général De Gaulle, 84231 Châteauneuf-du-Pape"
          telephone: "%app_drev_CHATEAUNEUFDUPAPE_telephone%"
          email: "%app_drev_CHATEAUNEUFDUPAPE_email%"
          produits:
            - "TRANQ/appellations/CDP"
          habilitation_produits: "/Chateauneuf du Pape/"
        LIRAC:
          nom: "Syndicat de l'AOC Lirac"
          adresse: "Chemin des Chênes, 30126 Lirac"
          telephone: "%app_drev_LIRAC_telephone%"
          email: "%app_drev_LIRAC_email%"
          produits:
            - "TRANQ/appellations/LIR"
          habilitation_produits: "/Lirac/"
        GIGONDAS:
          nom: "Syndicat de Gigondas "
          adresse: "8 rue du fond du sac, 84190 Gigondas"
          telephone: "%app_drev_GIGONDAS_telephone%"
          email: "%app_drev_GIGONDAS_email%"
          produits:
            - "TRANQ/appellations/GIG"
          habilitation_produits: "/Gigondas/"
        VACQUEYRAS:
          nom: "Syndicat de Vacqueyras"
          adresse: "158 route de Carpentras 84190 Vacqueyras"
          telephone: "%app_drev_VACQUEYRAS_telephone%"
          email: "%app_drev_VACQUEYRAS_email%"
          produits:
            - "TRANQ/appellations/VAC"
          habilitation_produits: "/Vacqueyras/"
        RASTEAU:
          nom: "Syndicat des Vignerons de Rasteau"
          adresse: "1 place de l'Eglise 84110 Rasteau"
          telephone: "%app_drev_RASTEAU_telephone%"
          email: "%app_drev_RASTEAU_email%"
          produits:
            - "TRANQ/appellations/RTA"
            - "VDN/appellations/VDR"
          habilitation_produits: "/Rasteau/"
        TAVEL:
          nom: "Syndicat AOC Tavel"
          adresse: "56 Chemin de la Croix d’Alix 30126 Tavel"
          telephone: "%app_drev_TAVEL_telephone%"
          email: "%app_drev_TAVEL_email%"
          produits:
            - "TRANQ/appellations/TAV"
          habilitation_produits: "/Tavel/"
