all:
  configuration:
    societe:
      droits:
        "ADMIN": "Administrateur"
        "habilitation": "Habilitation"
        "habilitation:inao": "Habilitation INAO"
        "habilitation:oivr": "Habilitation OIVR"
        "habilitation:odg": "Habilitation ODG"
        "habilitation:certipaq": "Habilitation CERTIPAQ"
        "api": "API"
        "timbre": "Timbre"
        "stalker": "Stalker"
        "teledeclaration_drev_admin": "ODG RÃ©gion"
      visualisation_teledeclaration: true
