# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  organisme:
    nom: "Syndicat des Vins Côtes de Provence"
  elasticversion: '2.4.6'
  document_validation_signataire: 1
  parcellaire_irrigable:
    ressources: ["Canal de Provence", "Forage", "Etang", "Retenue collinaire","Réseau urbain"]
    materiels: ["Goutte à goutte", "Canon", "Système enterré"]
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "CDP%05d"
  donnees_viticoles:
    regions:
      ALPES_MARITIMES_83: "ALPES MARITIMES (83)"
      ARGENS_BESSILLON_83: "ARGENS BESSILLON (83)"
      BASSIN_DU_BEAUSSET_13: "BASSIN DU BEAUSSET (13)"
      BASSIN_DU_BEAUSSET_83: "BASSIN DU BEAUSSET (83)"
      DRACENIE_83: "DRACENIE (83)"
      FREJUS_83: "FREJUS (83)"
      GOLF_DE_ST_TROPEZ_83: "GOLF DE ST TROPEZ (83)"
      LA_LONDE_83: "LA LONDE (83)"
      MAURES_INTERIEURS_83: "MAURES INTERIEURS (83)"
      NOTRE_DAME_DES_ANGES_83: "NOTRE DAME DES ANGES (83)"
      PIERREFEU_13: "PIERREFEU (13)"
      PIERREFEU_83: "PIERREFEU (83)"
      PLATEAU_KARSTIQUE_83: "PLATEAU KARSTIQUE (83)"
      SAINTE_VICTOIRE_13: "SAINTE VICTOIRE (13)"
      SAINTE_VICTOIRE_83: "SAINTE VICTOIRE (83)"
  communes: 
    denominations: 
      NDA : [83004,83033,83134,83148,83031,83063,83073,83075,83067,83092]
      SVI : [13025,13109,13060,13072,13079,13087,13110, 83096, 83097]
      FRE : [83028,83061,83085,83086,83099,83107,83118,83141]
      PIE : [83033,83034,83043,83049,83054,83062,83144,83098,83091,83100,83130,83047]
      LLO : [83019,83047,83069,83071]
  potentielproductiongenerator: "PotentielProductionProvenceGenerator"
