all:
  configuration:
    facture:
      ligneUnique: false
      ligneDetailWithTitle: false
      echeances: false
      all_etablissements: false
      export_sage_width_txt: true
      all_etablissements: true
      modalite_paiement: "Payable par virement, IBAN : %iban%\\En votre aimable règlement à réception."
      uniq_template_prefix: "TEMPLATE-FACTURE"
      paiements: true
