all:
  configuration:
    degustation:
      nb_etiquettes: 4
      anonymisation_manuelle: true
      tournees_par_secteur: true
      typicite_cepage: false
      conformite:
        - CONFORME
        - NONCONFORME_ANALYTIQUE
        - NONCONFORME_ORGANOLEPTIQUE
      has_degustateur_par_region: true
