all:
  configuration:
    region:
      oc: OIVC
      odg:
        SANCERRE:
         #  nom: "Conservatoire AOC Beaumes Venise"
         # adresse: "Place du marché à coté de la poste, 84190 Beaumes-de-Venise"
         # telephone: "%app_drev_BEAUMESVENISES_telephone%"
         # email: "%app_drev_BEAUMESVENISES_email%"
          produits:
            - "TRANQ/appellations/SCR"
          habilitation_produits: "/Sancerre/"
          facture_block_missing: true
        POUILLY:
          # nom: "Syndicat de l’AOC Cairanne"
          # adresse: "6 place des Vignerons, 84290 CAIRANNE"
          # telephone: "%app_drev_CAIRANNE_telephone%"
          # email: "%app_drev_CAIRANNE_email%"
          produits:
            - "TRANQ/appellations/PFM"
            - "TRANQ/appellations/PSL"
          habilitation_produits:  "/Pouilly/"
          facture_block_missing: true
        MENETOUSALON:
          # nom: "Comité des Vignerons de Vinsobres"
          # adresse: "8 rue Gironde, 26110 Vinsobres"
          # telephone: "%app_drev_VINSOBRES_telephone%"
          # email: "%app_drev_VINSOBRES_email%"
          produits:
            - "TRANQ/appellations/MTS"
          habilitation_produits: "/Menetou-Salon/"
          facture_exercice: 'viticole'
        QUINCY:
          # nom: "Syndicat des Vignerons de Châteauneuf-du-Pape"
          # adresse: "25 avenue Général De Gaulle, 84231 Châteauneuf-du-Pape"
          # telephone: "%app_drev_CHATEAUNEUFDUPAPE_telephone%"
          # email: "%app_drev_CHATEAUNEUFDUPAPE_email%"
          produits:
            - "TRANQ/appellations/QCY"
          habilitation_produits: "/Quincy/"
        REUILLY:
          # nom: "Syndicat de l'AOC Lirac"
          # adresse: "Chemin des Chênes, 30126 Lirac"
          # telephone: "%app_drev_LIRAC_telephone%"
          # email: "%app_drev_LIRAC_email%"
          produits:
            - "TRANQ/appellations/RLY"
          habilitation_produits: "/Reuilly/"
        CHATEAUMEILLANT:
          # nom: "Syndicat de Gigondas "
          # adresse: "8 rue du fond du sac, 84190 Gigondas"
          # telephone: "%app_drev_GIGONDAS_telephone%"
          # email: "%app_drev_GIGONDAS_email%"
          produits:
            - "TRANQ/appellations/CHM"
          habilitation_produits: "/Châteaumeillant/"
        GIENNOIS:
          # nom: "Syndicat de Vacqueyras"
          # adresse: "158 route de Carpentras 84190 Vacqueyras"
          # telephone: "%app_drev_VACQUEYRAS_telephone%"
          # email: "%app_drev_VACQUEYRAS_email%"
          produits:
            - "TRANQ/appellations/CDG"
          habilitation_produits: "/Coteaux du Giennois/"
