# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: IE=edge

  metas:
    title:            "Plateforme de télédéclaration vinsdenantes.com"
    charset:          "utf-8"
    description:      "Plateforme de télédéclaration vinsdenantes.com"
    robots:           "index,follow"
    content-language: "fr-FR"
    viewport:         "width=device-width, initial-scale=1"

  stylesheets:    [compile_nantes.css?201706281900: { media: all }, print.css: { media: print }, ../components/vins/vins.css: { media: all }, /js/lib/leaflet/leaflet.css]
  javascripts:    [lib/jquery/jquery.min.js, lib/jquery.plugins.min.js?201709221633, lib/bootstrap/bootstrap.min.js, lib/bootstrap3-typeahead.min.js, lib/bootstrap-switch.min.js, lib/leaflet/leaflet.js, global.js?20201123, compte.js, drev.js?201912031729, drevmarc.js, form.js?201801171851, parcellaire.js, ava.js]

  has_layout:     true
  layout:         layout
