# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  routing_context_production_host: sudouest.igp.vins.24eme.fr
  organisme:
    nom: "Fédération Régionale des Vins IGP du Sud-Ouest"
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "FRS%06d"
  donnees_viticoles:
    regions:
      IGPSUDOUEST: "IGPSUDOUEST"
    secteurs:
      ARIEGE: "ARIEGE"
      AVEYRON: "AVEYRON"
      CANTAL: "CANTAL"
      HAUTE-GARONNE: "HAUTE-GARONNE"
      LANDES: "LANDES"
      LOT: "LOT"
      LOT-ET-GARONNE: "LOT-ET-GARONNE"
      PYRENEES-ATLANTIQUE: "PYRENEES-ATLANTIQUE"
      TARN-ET-GARONNE: "TARN-ET-GARONNE"
  etiquettes: "70x36" #Impression en taille rélle
  email_plugin_all_copy: true
