all:
  configuration:
    drev:
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: 'admin'
      notif_pour_approbation: true
      etape_superficie: false
      dr_douane_required: false
      degustation: true
      specificite_lot: true
      engagement_pdf: true
