all:
  configuration:
    drev:
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: 'auto'
      etape_superficie: false
      dr_douane_required: false
      degustation: true
      specificite_lot: true
      engagement_pdf: true
      volume_seuil:
        campagne: 2022-2023
      specificites:
        bio: "bio"
        HVE: "HVE"
        autre: "Autre"
        TerraVitis: "Terra Vitis"
