all:
  configuration:
    facture:
      aggregateMouvements: false
      ligneMsg: false
      echeances: false
      all_etablissements: false
      export_sage_width_txt: true
      all_etablissements: true
      modalite_paiement: "Par chèque à l'ordre de «ODG 13» et à adresser au Syndicat des Vignerons d'Arles"
      uniq_template_prefix: "TEMPLATE-FACTURE"
      paiements: true
      exercice: "viticole"
