all:
  configuration:
    facture:
      ligneUnique: true
      suggestions_facturation_libre: ["Frais de déplacement|0.631", "Temps passé|31.00"]
      uniq_template_prefix: "TEMPLATE-FACTURE-%region%"
      export_type: "custom"
      exercice: "viticole"
      delais_paiement: '+30 days'
