# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: IE=edge

  metas:
    title:            "Plateforme de télédéclaration de l'AVA"
    charset:          "utf-8"
    description:      "Plateforme de télédéclaration de l'AVA"
    robots:           "index,follow"
    content-language: "fr-FR"
    viewport:         "width=device-width, initial-scale=1"

  stylesheets:    [compile.css?201709151030: { media: all }, print.css: { media: print }, ../components/vins/vins.css: { media: all }]

  javascripts:    [lib/jquery/jquery.min.js, lib/jquery.plugins.min.js, lib/bootstrap/bootstrap.min.js, lib/bootstrap3-typeahead.min.js, lib/bootstrap-switch.min.js, global.js?201710131239, compte.js, drev.js?20151126, drevmarc.js, form.js, parcellaire.js, ava.js]

  has_layout:     true
  layout:         layout
