all:
  configuration:
    parcellaire:
      ecart_rangs_max: 250
      ecart_pieds_max: 250
      ecart_pieds_min:  80
      manquant:
        pc_min: 20
      affectation:
        needs_intention: false
      aires:
        Ventoux:
          name: "Ventoux"
          color: "#ab3f97"
          denomination_id: "01363"
      declarations_liees: true
      parcelles_from_affectationparcellaire: true
      show_filter_produits_configuration: true
      troisieme_feuille: false #en 4Ã¨me feuille
