all:
  configuration:
    degustation:
      specificite_lot_pdf: true
      colleges:
        degustateur_technicien: "Technicien"
        degustateur_porteur_de_memoire: "Porteur de m√©moire"
        degustateur_usager_du_produit: "Usager du produit"
      conformite:
        - CONFORME
        - NONCONFORME_MINEUR
        - NONCONFORME_MAJEUR
        - NONCONFORME_GRAVE
        - NONTYPICITE_CEPAGE
        - NONCONFORME_ANALYTIQUE
      has_notification: true
