all:
  configuration:
    degustation:
      anonymat4labo: true
      specificite_lot_pdf: true
      always_identifiant_table: true
      conformite:
        - CONFORME
        - NONCONFORME_MINEUR
        - NONCONFORME_MAJEUR
        - NONCONFORME_GRAVE
        - NONTYPICITE_CEPAGE
        - NONCONFORME_ANALYTIQUE
      has_notification: true
