all:
  configuration:
    degustation:
      anonymat4labo: true
      specificite_lot_pdf: false
      always_identifiant_table: true
      is_acceptable:
        aocgaillac : true
        igptarn : false
      conformite:
        - CONFORME
        - NONCONFORME_MINEUR
        - NONCONFORME_MAJEUR
        - NONCONFORME_GRAVE
        - NONTYPICITE_CEPAGE
        - NONCONFORME_ANALYTIQUE
      has_notification: true
      has_degustateur_par_region: false
