all:
  configuration:
    drev:
      prelevements: false
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: 'auto'
      etape_superficie: true
      etapes_aoc: true
      dr_douane_required: false
      degustation: true
      specificite_lot: true
      engagement_pdf: true
      specificites:
        bio: "bio"
        HVE: "HVE"
        autre: "Autre"
