all:
  configuration:
    region:
      odg:
        AOCGAILLAC:
          # nom: ""
          # adresse: ""
          # telephone: ""
          # email: ""
          produits:
            - "TRANQ/appellations/GLC"
            - "TRANQ/appellations/GPC"
            - "MOU/appellations/GLC"
            - "VDB/appellations/GLC"
          habilitation_produits: "/Gaillac/"
        IGPTARN:
          # nom: ""
          # adresse: ""
          # telephone: ""
          # email: ""
          produits:
            - "TRANQ/appellations/CDT"
            - "TRANQ/appellations/COT"
            - "MOU/appellations/COT"
          habilitation_produits: "/CÃ´tes du Tarn/"
