# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: IE=edge

  metas:
    title:            "Plateforme de télédéclaration des Vins de Gaillac"
    charset:          "utf-8"
    description:      "Plateforme de télédéclaration des Vins de Gaillac"
    robots:           "index,follow"
    content-language: "fr-FR"
    viewport:         "width=device-width, initial-scale=1"

  stylesheets:    [compile_default.css, ../components/vins/vins.css, /js/lib/leaflet/leaflet.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
