all:
  configuration:
    facture:
      aggregateMouvements: false
      ligneMsg: false
      echeances: false
      all_etablissements: false
      export_sage_width_txt: true
      all_etablissements: true
      numero_campagne: true
      numero_format: "%02d%05d"
      modalite_paiement: "- comptant  par virement \\ - virement en 3, 6, 8 ou 9 fois de mars 2020 à novembre 2020 \\ - prélèvement automatique en 9 fois de mars 2020 à novembre 2020 \\"
      uniq_template_prefix: "TEMPLATE-FACTURE"
      paiements: true
